import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedGIFTOFTHEGIVERSWidget1.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedCOLLECTIONCENTERWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedHOMEWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedSIGNUPASWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedNGOWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedDONORWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_upwidget/generated/GeneratedRectangle13Widget.dart';

/* Frame Sign_Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSign_UpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 53.0,
              top: 426.0,
              right: null,
              bottom: null,
              width: 259.9999694824219,
              height: 53.0,
              child: GeneratedRectangle11Widget(),
            ),
            Positioned(
              left: 53.0,
              top: 343.0,
              right: null,
              bottom: null,
              width: 259.9999694824219,
              height: 53.0,
              child: GeneratedRectangle12Widget(),
            ),
            Positioned(
              left: 53.0,
              top: 251.0,
              right: null,
              bottom: null,
              width: 259.9999694824219,
              height: 53.0,
              child: GeneratedRectangle13Widget(),
            ),
            Positioned(
              left: 71.99998474121094,
              top: 268.79913330078125,
              right: null,
              bottom: null,
              width: 225.80787658691406,
              height: 24.0,
              child: GeneratedDONORWidget(),
            ),
            Positioned(
              left: 69.99998474121094,
              top: 356.5633544921875,
              right: null,
              bottom: null,
              width: 228.3755645751953,
              height: 40.0,
              child: GeneratedCOLLECTIONCENTERWidget(),
            ),
            Positioned(
              left: 107.0,
              top: 443.0,
              right: null,
              bottom: null,
              width: 156.0,
              height: 24.0,
              child: GeneratedNGOWidget(),
            ),
            Positioned(
              left: 44.999996185302734,
              top: 130.28382873535156,
              right: null,
              bottom: null,
              width: 278.48468017578125,
              height: 140.29258728027344,
              child: GeneratedSIGNUPASWidget(),
            ),
            Positioned(
              left: 57.0,
              top: 62.0,
              right: null,
              bottom: null,
              width: 252.00003051757812,
              height: 42.0,
              child: GeneratedGIFTOFTHEGIVERSWidget1(),
            ),
            Positioned(
              left: 166.0,
              top: 571.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 29.0,
              child: GeneratedRectangle10Widget1(),
            ),
            Positioned(
              left: 147.0,
              top: 581.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 24.0,
              child: GeneratedHOMEWidget(),
            )
          ]),
    ));
  }
}
