import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedGIFTOFTHEGIVERSWidget10.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedRectangle28Widget6.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedRectangle45Widget1.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedBeforeyoudonatepleasenotewhatourpartnershavetoldusabout1.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedDonateNowWidget1.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedBACKWidget5.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedHOTLISTWidget3.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedHOMEWidget12.dart';
import 'package:flutterapp/giftapp/generatedhotlist_ccwidget/generated/GeneratedRectangle13Widget5.dart';

/* Frame HOTLIST_CC
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOTLIST_CCWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 107.47826385498047,
                top: 90.0,
                right: null,
                bottom: null,
                width: 145.04348754882812,
                height: 71.57894897460938,
                child: GeneratedRectangle28Widget6(),
              ),
              Positioned(
                left: 71.47826385498047,
                top: 172.63156127929688,
                right: null,
                bottom: null,
                width: 208.60867309570312,
                height: 29.894744873046875,
                child:
                    GeneratedBeforeyoudonatepleasenotewhatourpartnershavetoldusabout1(),
              ),
              Positioned(
                left: 0.0,
                top: 45.26315689086914,
                right: null,
                bottom: null,
                width: 365.0,
                height: 64.47369003295898,
                child: GeneratedHOTLISTWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 62.0,
                child: GeneratedGIFTOFTHEGIVERSWidget10(),
              ),
              Positioned(
                left: 25.043481826782227,
                top: 577.894775390625,
                right: null,
                bottom: null,
                width: 93.06322479248047,
                height: 25.14019775390625,
                child: GeneratedRectangle15Widget3(),
              ),
              Positioned(
                left: 32.7075080871582,
                top: 584.663330078125,
                right: null,
                bottom: null,
                width: 83.83004760742188,
                height: 23.37164306640625,
                child: GeneratedBACKWidget5(),
              ),
              Positioned(
                left: 229.04348754882812,
                top: 533.6842041015625,
                right: null,
                bottom: null,
                width: 114.2608642578125,
                height: 44.2105712890625,
                child: GeneratedRectangle13Widget5(),
              ),
              Positioned(
                left: 234.7825927734375,
                top: 543.1578979492188,
                right: null,
                bottom: null,
                width: 103.2174072265625,
                height: 32.0,
                child: GeneratedDonateNowWidget1(),
              ),
              Positioned(
                left: 25.043481826782227,
                top: 530.5263061523438,
                right: null,
                bottom: null,
                width: 93.06322479248047,
                height: 25.1402587890625,
                child: GeneratedRectangle45Widget1(),
              ),
              Positioned(
                left: 32.707542419433594,
                top: 537.294921875,
                right: null,
                bottom: null,
                width: 83.83003997802734,
                height: 23.37164306640625,
                child: GeneratedHOMEWidget12(),
              ),
              Positioned(
                left: 32.86956787109375,
                top: 228.4208984375,
                right: null,
                bottom: null,
                width: 292.21734619140625,
                height: 279.4743347167969,
                child: GeneratedGroup29Widget(),
              )
            ]),
      ),
    ));
  }
}
