import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedPhysicalAddressWidget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedLatudinalcoordinateWidget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedSavechangesWidget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedEmailAddressWidget3.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedUser_idWidget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedPROFILEWidget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle26Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedContactnumberWidget2.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedPhysicalAddressWidget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedLongitudinalcoordinateWidget.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/giftapp/generatedprofile_donorwidget/generated/GeneratedFrame7Widget.dart';

/* Frame Profile_Donor
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfile_DonorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 208.4291229248047,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45531463623047,
                child: GeneratedRectangle21Widget2(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 265.3349304199219,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.455360412597656,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 322.24078369140625,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.455299377441406,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 379.9157409667969,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45526885986328,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 432.1731262207031,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45526885986328,
                child: GeneratedRectangle25Widget1(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 484.8934631347656,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45532989501953,
                child: GeneratedRectangle26Widget1(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 182.68197631835938,
                right: null,
                bottom: null,
                width: 311.93463134765625,
                height: 14.712646484375,
                child: GeneratedFrame7Widget(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 239.6827392578125,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedContactnumberWidget2(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 298.5332946777344,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedEmailAddressWidget3(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 357.38385009765625,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedPhysicalAddressWidget(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 357.38385009765625,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedPhysicalAddressWidget1(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 411.3302307128906,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedLongitudinalcoordinateWidget(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 464.050537109375,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.842926025390625,
                child: GeneratedLatudinalcoordinateWidget(),
              ),
              Positioned(
                left: 100.90908813476562,
                top: 570.1149291992188,
                right: null,
                bottom: null,
                width: 162.27273559570312,
                height: 51.49420166015625,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 113.18181610107422,
                top: 570.1149291992188,
                right: null,
                bottom: null,
                width: 141.0909423828125,
                height: 53.49420166015625,
                child: GeneratedSavechangesWidget(),
              ),
              Positioned(
                left: 112.8065414428711,
                top: 51.49425506591797,
                right: null,
                bottom: null,
                width: 143.18182373046875,
                height: 85.8237533569336,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 77.4931869506836,
                top: 137.31800842285156,
                right: null,
                bottom: null,
                width: 210.90908813476562,
                height: 38.10343933105469,
                child: GeneratedUser_idWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 61.33802795410156,
                child: GeneratedPROFILEWidget(),
              )
            ]),
      ),
    ));
  }
}
