import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedHOMEWidget11.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedDonateWidget.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedRectangle44Widget1.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedRectangle43Widget3.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedBACKWidget4.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedRectangle42Widget3.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedGIFTOFTHEGIVERSWidget9.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedMONEYWidget.dart';
import 'package:flutterapp/giftapp/generateddonate_pwidget/generated/GeneratedPERISHABLESWidget.dart';

/* Frame DONATE_P
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDONATE_PWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 260.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 94.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 51.0,
                child: GeneratedRectangle28Widget2(),
              ),
              Positioned(
                left: -4.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 25.313400268554688,
                child: GeneratedGIFTOFTHEGIVERSWidget9(),
              ),
              Positioned(
                left: -7.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 28.313400268554688,
                child: GeneratedDonateWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 191.34375,
                right: null,
                bottom: null,
                width: 316.4912109375,
                height: 35.67509460449219,
                child: GeneratedRectangle42Widget3(),
              ),
              Positioned(
                left: 15.0,
                top: 191.34375,
                right: null,
                bottom: null,
                width: 321.4912414550781,
                height: 40.67506408691406,
                child: GeneratedPERISHABLESWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 145.84375,
                right: null,
                bottom: null,
                width: 316.4912109375,
                height: 35.67510986328125,
                child: GeneratedRectangle43Widget3(),
              ),
              Positioned(
                left: 15.0,
                top: 149.90625,
                right: null,
                bottom: null,
                width: 321.4912109375,
                height: 40.67510986328125,
                child: GeneratedMONEYWidget(),
              ),
              Positioned(
                left: 8.421052932739258,
                top: 232.8869171142578,
                right: null,
                bottom: null,
                width: 125.17277526855469,
                height: 13.632583618164062,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 18.729440689086914,
                top: 236.55726623535156,
                right: null,
                bottom: null,
                width: 111.0287094116211,
                height: 14.962234497070312,
                child: GeneratedBACKWidget4(),
              ),
              Positioned(
                left: 208.42105102539062,
                top: 232.8869171142578,
                right: null,
                bottom: null,
                width: 125.17276000976562,
                height: 13.632583618164062,
                child: GeneratedRectangle44Widget1(),
              ),
              Positioned(
                left: 218.7294464111328,
                top: 236.55726623535156,
                right: null,
                bottom: null,
                width: 111.02870178222656,
                height: 14.962234497070312,
                child: GeneratedHOMEWidget11(),
              )
            ]),
      ),
    ));
  }
}
