import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedreq_submitwidget/generated/GeneratedYourrequesthasbeenloggedanemailwithmoredetailsofyourord.dart';
import 'package:flutterapp/giftapp/generatedreq_submitwidget/generated/GeneratedDonationRequestSubmittedWidget.dart';
import 'package:flutterapp/giftapp/generatedreq_submitwidget/generated/GeneratedRectangle29Widget6.dart';
import 'package:flutterapp/giftapp/generatedreq_submitwidget/generated/GeneratedRectangle30Widget2.dart';
import 'package:flutterapp/giftapp/generatedreq_submitwidget/generated/GeneratedHomeWidget.dart';

/* Frame Req_Submit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReq_SubmitWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 181.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 58.33802795410156,
                child: GeneratedDonationRequestSubmittedWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 41.0,
                child: GeneratedRectangle29Widget6(),
              ),
              Positioned(
                left: 18.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 50.0,
                child:
                    GeneratedYourrequesthasbeenloggedanemailwithmoredetailsofyourord(),
              ),
              Positioned(
                left: 106.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 27.0,
                child: GeneratedRectangle30Widget2(),
              ),
              Positioned(
                left: 150.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 52.0,
                child: GeneratedHomeWidget(),
              )
            ]),
      ),
    ));
  }
}
