import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedConfirmPasswordWidget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedSignupWidget4.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedEmailAddressWidget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedPhonenumberWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedHOMEWidget2.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedSignupasaDonorWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedBACKWidget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedCreatePasswordWidget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_donorwidget/generated/GeneratedGIFTOFTHEGIVERSWidget3.dart';

/* Frame Sign_Up_Donor
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSign_Up_DonorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 198.15631103515625,
                right: null,
                bottom: null,
                width: 321.0019836425781,
                height: 37.72705841064453,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 277.8317565917969,
                right: null,
                bottom: null,
                width: 321.0019836425781,
                height: 37.72705841064453,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 519.1887817382812,
                right: null,
                bottom: null,
                width: 321.0019836425781,
                height: 37.727149963378906,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 438.3480529785156,
                right: null,
                bottom: null,
                width: 321.0019836425781,
                height: 37.727088928222656,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 358.6724853515625,
                right: null,
                bottom: null,
                width: 321.0019836425781,
                height: 37.72705841064453,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 120.81122589111328,
                right: null,
                bottom: null,
                width: 326.1230773925781,
                height: 42.940711975097656,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 199.68798828125,
                right: null,
                bottom: null,
                width: 323.1230773925781,
                height: 39.94071960449219,
                child: GeneratedPhonenumberWidget(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 280.5616149902344,
                right: null,
                bottom: null,
                width: 323.1230773925781,
                height: 40.93914794921875,
                child: GeneratedEmailAddressWidget1(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 441.3104553222656,
                right: null,
                bottom: null,
                width: 323.1230773925781,
                height: 39.940704345703125,
                child: GeneratedConfirmPasswordWidget1(),
              ),
              Positioned(
                left: 19.438446044921875,
                top: 360.43682861328125,
                right: null,
                bottom: null,
                width: 323.1230773925781,
                height: 39.940704345703125,
                child: GeneratedCreatePasswordWidget1(),
              ),
              Positioned(
                left: 10.885529518127441,
                top: 593.0733032226562,
                right: null,
                bottom: null,
                width: 97.96976470947266,
                height: 33.94696044921875,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 293.1317443847656,
                top: 591.076416015625,
                right: null,
                bottom: null,
                width: 38.099365234375,
                height: 37.94073486328125,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 271.3607177734375,
                top: 603.0577392578125,
                right: null,
                bottom: null,
                width: 88.196533203125,
                height: 29.96099853515625,
                child: GeneratedHOMEWidget2(),
              ),
              Positioned(
                left: 139.95680236816406,
                top: 540.1560668945312,
                right: null,
                bottom: null,
                width: 91.74946594238281,
                height: 37.940673828125,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 143.84449768066406,
                top: 548.1435546875,
                right: null,
                bottom: null,
                width: 85.196533203125,
                height: 26.9609375,
                child: GeneratedSignupWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 12.979719161987305,
                right: null,
                bottom: null,
                width: 356.5572509765625,
                height: 72.88922119140625,
                child: GeneratedGIFTOFTHEGIVERSWidget3(),
              ),
              Positioned(
                left: 10.885529518127441,
                top: 601.0608520507812,
                right: null,
                bottom: null,
                width: 88.19654846191406,
                height: 29.96099853515625,
                child: GeneratedBACKWidget1(),
              ),
              Positioned(
                left: 76.1987075805664,
                top: 57.909515380859375,
                right: null,
                bottom: null,
                width: 200.27215576171875,
                height: 60.907958984375,
                child: GeneratedSignupasaDonorWidget(),
              )
            ]),
      ),
    ));
  }
}
