import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedForgotpasswordWidget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedGIFTOFTHEGIVERSWidget5.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedHOMEWidget5.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedDonthaveanaccountSignupWidget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedHOMEWidget4.dart';
import 'package:flutterapp/giftapp/generatedlog_in_donorwidget/generated/GeneratedRectangle13Widget1.dart';

/* Frame Log_in_Donor
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLog_in_DonorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.7647058963775635,
                top: 28.571430206298828,
                right: null,
                bottom: null,
                width: 362.00006103515625,
                height: 86.59770202636719,
                child: GeneratedGIFTOFTHEGIVERSWidget5(),
              ),
              Positioned(
                left: 89.33332824707031,
                top: 180.22988891601562,
                right: null,
                bottom: null,
                width: 167.33331298828125,
                height: 47.36399841308594,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 48.00000762939453,
                top: 386.2069091796875,
                right: null,
                bottom: null,
                width: 263.400146484375,
                height: 63.497802734375,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 48.00000762939453,
                top: 274.63604736328125,
                right: null,
                bottom: null,
                width: 263.400146484375,
                height: 63.497772216796875,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 52.738853454589844,
                top: 243.8918914794922,
                right: null,
                bottom: null,
                width: 160.923583984375,
                height: 25.756729125976562,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 52.738853454589844,
                top: 350.270263671875,
                right: null,
                bottom: null,
                width: 160.923583984375,
                height: 25.7567138671875,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 85.2631607055664,
                top: 489.67742919921875,
                right: null,
                bottom: null,
                width: 191.17196655273438,
                height: 22.7567138671875,
                child: GeneratedForgotpasswordWidget(),
              ),
              Positioned(
                left: 155.92161560058594,
                top: 588.5713500976562,
                right: null,
                bottom: null,
                width: 43.99998474121094,
                height: 35.55572509765625,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 130.58824157714844,
                top: 599.6060180664062,
                right: null,
                bottom: null,
                width: 101.00001525878906,
                height: 28.2950439453125,
                child: GeneratedHOMEWidget4(),
              ),
              Positioned(
                left: 130.58824157714844,
                top: 599.6060180664062,
                right: null,
                bottom: null,
                width: 101.00001525878906,
                height: 28.2950439453125,
                child: GeneratedHOMEWidget5(),
              ),
              Positioned(
                left: 252.07022094726562,
                top: 454.19354248046875,
                right: null,
                bottom: null,
                width: 44.0,
                height: 35.555755615234375,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 186.94737243652344,
                top: 466.4515686035156,
                right: null,
                bottom: null,
                width: 179.94737243652344,
                height: 28.225860595703125,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 518.09521484375,
                right: null,
                bottom: null,
                width: 362.0,
                height: 47.7142333984375,
                child: GeneratedDonthaveanaccountSignupWidget(),
              )
            ]),
      ),
    ));
  }
}
