import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedSignupasaNGOWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedCreatePasswordWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedGIFTOFTHEGIVERSWidget2.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedHOMEWidget1.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedSignupWidget3.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedBACKWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedEmailAddressWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedNameofOrganisationWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/giftapp/generatedsign_up_ngowidget/generated/GeneratedContactnumberWidget.dart';

/* Frame Sign_Up_NGO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSign_Up_NGOWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 40.62992477416992,
                top: 176.55172729492188,
                right: null,
                bottom: null,
                width: 278.5714416503906,
                height: 39.00463104248047,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 40.62992477416992,
                top: 254.55499267578125,
                right: null,
                bottom: null,
                width: 278.5714416503906,
                height: 39.004615783691406,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 40.62992477416992,
                top: 332.55804443359375,
                right: null,
                bottom: null,
                width: 278.5714416503906,
                height: 39.00464630126953,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 40.62992477416992,
                top: 411.615478515625,
                right: null,
                bottom: null,
                width: 278.5714416503906,
                height: 39.004676818847656,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 40.62992477416992,
                top: 489.61871337890625,
                right: null,
                bottom: null,
                width: 278.5714416503906,
                height: 39.004554748535156,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 97.6321792602539,
                child: GeneratedGIFTOFTHEGIVERSWidget2(),
              ),
              Positioned(
                left: 19.842493057250977,
                top: 72.33716583251953,
                right: null,
                bottom: null,
                width: 322.4546203613281,
                height: 60.85059356689453,
                child: GeneratedSignupasaNGOWidget(),
              ),
              Positioned(
                left: 49.133880615234375,
                top: 150.80458068847656,
                right: null,
                bottom: null,
                width: 263.818115234375,
                height: 27.747146606445312,
                child: GeneratedNameofOrganisationWidget(),
              ),
              Positioned(
                left: 68.03150939941406,
                top: 221.91571044921875,
                right: null,
                bottom: null,
                width: 225.63633728027344,
                height: 17.938690185546875,
                child: GeneratedContactnumberWidget(),
              ),
              Positioned(
                left: 102.04722595214844,
                top: 300.3831481933594,
                right: null,
                bottom: null,
                width: 158.8181610107422,
                height: 27.747100830078125,
                child: GeneratedEmailAddressWidget(),
              ),
              Positioned(
                left: 66.14175415039062,
                top: 459.77008056640625,
                right: null,
                bottom: null,
                width: 229.72723388671875,
                height: 21.6168212890625,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: 66.14171600341797,
                top: 380.07659912109375,
                right: null,
                bottom: null,
                width: 229.72720336914062,
                height: 25.2950439453125,
                child: GeneratedCreatePasswordWidget(),
              ),
              Positioned(
                left: 278.18182373046875,
                top: 593.4099731445312,
                right: null,
                bottom: null,
                width: 45.0,
                height: 35.55560302734375,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 13.636363983154297,
                top: 597.0880126953125,
                right: null,
                bottom: null,
                width: 115.90908813476562,
                height: 31.8775634765625,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 252.272705078125,
                top: 604.4443969726562,
                right: null,
                bottom: null,
                width: 103.18185424804688,
                height: 28.2950439453125,
                child: GeneratedHOMEWidget1(),
              ),
              Positioned(
                left: 23.18181800842285,
                top: 605.6705322265625,
                right: null,
                bottom: null,
                width: 103.18182373046875,
                height: 28.2950439453125,
                child: GeneratedBACKWidget(),
              ),
              Positioned(
                left: 120.94482421875,
                top: 545.5939331054688,
                right: null,
                bottom: null,
                width: 118.63632202148438,
                height: 45.36395263671875,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 131.3385772705078,
                top: 556.62841796875,
                right: null,
                bottom: null,
                width: 100.18180847167969,
                height: 25.29498291015625,
                child: GeneratedSignupWidget3(),
              ),
              Positioned(
                left: 120.94482421875,
                top: 545.5939331054688,
                right: null,
                bottom: null,
                width: 118.63632202148438,
                height: 45.36395263671875,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 131.3385772705078,
                top: 555.4022827148438,
                right: null,
                bottom: null,
                width: 103.18180847167969,
                height: 28.2950439453125,
                child: GeneratedSubmitWidget(),
              )
            ]),
      ),
    ));
  }
}
