import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedEmailAddressWidget4.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedPhysicalAddressWidget3.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedLatudinalcoordinateWidget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedPhysicalAddressWidget2.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedFrame7Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedContactnumberWidget3.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle25Widget2.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle26Widget2.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedLongitudinalcoordinateWidget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedUser_idWidget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle24Widget3.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle21Widget3.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedSavechangesWidget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedPROFILEWidget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/giftapp/generatedprofile_ngowidget/generated/GeneratedRectangle22Widget2.dart';

/* Frame Profile_NGO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfile_NGOWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 208.4291229248047,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45531463623047,
                child: GeneratedRectangle21Widget3(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 265.3349304199219,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.455360412597656,
                child: GeneratedRectangle22Widget2(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 322.24078369140625,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.455299377441406,
                child: GeneratedRectangle23Widget1(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 379.9157409667969,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45526885986328,
                child: GeneratedRectangle24Widget2(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 432.1731262207031,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45526885986328,
                child: GeneratedRectangle25Widget2(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 484.8934631347656,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45532989501953,
                child: GeneratedRectangle26Widget2(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 182.68197631835938,
                right: null,
                bottom: null,
                width: 311.93463134765625,
                height: 14.712646484375,
                child: GeneratedFrame7Widget1(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 239.6827392578125,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedContactnumberWidget3(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 298.5332946777344,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedEmailAddressWidget4(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 357.38385009765625,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedPhysicalAddressWidget2(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 357.38385009765625,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedPhysicalAddressWidget3(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 411.3302307128906,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.8428955078125,
                child: GeneratedLongitudinalcoordinateWidget1(),
              ),
              Positioned(
                left: 29.42779541015625,
                top: 464.050537109375,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.842926025390625,
                child: GeneratedLatudinalcoordinateWidget1(),
              ),
              Positioned(
                left: 100.90908813476562,
                top: 570.1149291992188,
                right: null,
                bottom: null,
                width: 162.27273559570312,
                height: 51.49420166015625,
                child: GeneratedRectangle24Widget3(),
              ),
              Positioned(
                left: 113.18181610107422,
                top: 570.1149291992188,
                right: null,
                bottom: null,
                width: 141.0909423828125,
                height: 53.49420166015625,
                child: GeneratedSavechangesWidget1(),
              ),
              Positioned(
                left: 112.8065414428711,
                top: 51.49425506591797,
                right: null,
                bottom: null,
                width: 143.18182373046875,
                height: 85.8237533569336,
                child: GeneratedRectangle29Widget1(),
              ),
              Positioned(
                left: 77.4931869506836,
                top: 137.31800842285156,
                right: null,
                bottom: null,
                width: 210.90908813476562,
                height: 38.10343933105469,
                child: GeneratedUser_idWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 61.33802795410156,
                child: GeneratedPROFILEWidget1(),
              )
            ]),
      ),
    ));
  }
}
