import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedHOMEWidget10.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedBACKWidget3.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedDonateNowWidget.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedHOTLISTWidget2.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedGIFTOFTHEGIVERSWidget8.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedRectangle13Widget4.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedBeforeyoudonatepleasenotewhatourpartnershavetoldusabout.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/giftapp/generatedhotlistwidget1/generated/GeneratedLine9Widget.dart';

/* Frame HOTLIST
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOTLISTWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 107.47826385498047,
                top: 90.0,
                right: null,
                bottom: null,
                width: 145.04348754882812,
                height: 71.57894897460938,
                child: GeneratedRectangle28Widget1(),
              ),
              Positioned(
                left: 71.47826385498047,
                top: 172.63156127929688,
                right: null,
                bottom: null,
                width: 208.60867309570312,
                height: 29.894744873046875,
                child:
                    GeneratedBeforeyoudonatepleasenotewhatourpartnershavetoldusabout(),
              ),
              Positioned(
                left: 0.0,
                top: 45.26315689086914,
                right: null,
                bottom: null,
                width: 365.0,
                height: 64.47369003295898,
                child: GeneratedHOTLISTWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 62.0,
                child: GeneratedGIFTOFTHEGIVERSWidget8(),
              ),
              Positioned(
                left: 25.043481826782227,
                top: 577.894775390625,
                right: null,
                bottom: null,
                width: 93.06322479248047,
                height: 25.14019775390625,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 32.7075080871582,
                top: 584.663330078125,
                right: null,
                bottom: null,
                width: 83.83004760742188,
                height: 23.37164306640625,
                child: GeneratedBACKWidget3(),
              ),
              Positioned(
                left: 229.04348754882812,
                top: 533.6842041015625,
                right: null,
                bottom: null,
                width: 114.2608642578125,
                height: 44.2105712890625,
                child: GeneratedRectangle13Widget4(),
              ),
              Positioned(
                left: 234.7825927734375,
                top: 543.1578979492188,
                right: null,
                bottom: null,
                width: 103.2174072265625,
                height: 32.0,
                child: GeneratedDonateNowWidget(),
              ),
              Positioned(
                left: 25.043481826782227,
                top: 530.5263061523438,
                right: null,
                bottom: null,
                width: 93.06322479248047,
                height: 25.1402587890625,
                child: GeneratedRectangle45Widget(),
              ),
              Positioned(
                left: 32.707542419433594,
                top: 537.294921875,
                right: null,
                bottom: null,
                width: 83.83003997802734,
                height: 23.37164306640625,
                child: GeneratedHOMEWidget10(),
              ),
              Positioned(
                left: 32.869564056396484,
                top: 507.8947448730469,
                right: null,
                bottom: null,
                width: 286.9949951171875,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 32.869564056396484,
                top: 230.0,
                right: null,
                bottom: null,
                width: 286.9949951171875,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 32.869564056396484,
                top: 230.0,
                right: null,
                bottom: null,
                width: 286.9949951171875,
                height: 1.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 32.86962890625,
                top: 228.4208984375,
                right: null,
                bottom: null,
                width: 290.0869140625,
                height: 279.4743347167969,
                child: GeneratedGroup28Widget(),
              )
            ]),
      ),
    ));
  }
}
