import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle29Widget3.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRequest_Donation_CCWidget1.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedDonationRequestWidget.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedSubmitWidget1.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedProductWidget2.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle24Widget6.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedDimensionsWidget.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle21Widget8.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedIfyouneedmoreitemsclicknextIfnotclicksubmtWidget.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedNextWidget.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedUser_idWidget6.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedQuantityWidget2.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle23Widget3.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle25Widget4.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedNameWidget4.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedGroup24Widget4.dart';
import 'package:flutterapp/giftapp/generatedrequest_donation_ccwidget/generated/GeneratedRectangle24Widget7.dart';

/* Frame Request_Donation_CC
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRequest_Donation_CCWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 208.4291229248047,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45531463623047,
                child: GeneratedRectangle21Widget8(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 322.24078369140625,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.455299377441406,
                child: GeneratedRectangle23Widget3(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 379.9157409667969,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45526885986328,
                child: GeneratedRectangle24Widget6(),
              ),
              Positioned(
                left: 28.446863174438477,
                top: 432.1731262207031,
                right: null,
                bottom: null,
                width: 311.9346618652344,
                height: 28.45526885986328,
                child: GeneratedRectangle25Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 316.93463134765625,
                height: 25.8428955078125,
                child: GeneratedProductWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 316.93463134765625,
                height: 25.8428955078125,
                child: GeneratedDimensionsWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 316.93463134765625,
                height: 25.8428955078125,
                child: GeneratedQuantityWidget2(),
              ),
              Positioned(
                left: 11.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 313.93463134765625,
                height: 22.842926025390625,
                child:
                    GeneratedIfyouneedmoreitemsclicknextIfnotclicksubmtWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 162.27273559570312,
                height: 51.49420166015625,
                child: GeneratedRectangle24Widget7(),
              ),
              Positioned(
                left: 194.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 162.27273559570312,
                height: 51.49420166015625,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 144.0909423828125,
                height: 56.49420166015625,
                child: GeneratedSubmitWidget1(),
              ),
              Positioned(
                left: 112.8065414428711,
                top: 51.49425506591797,
                right: null,
                bottom: null,
                width: 143.18182373046875,
                height: 85.8237533569336,
                child: GeneratedRectangle29Widget3(),
              ),
              Positioned(
                left: 77.4931869506836,
                top: 137.31800842285156,
                right: null,
                bottom: null,
                width: 210.90908813476562,
                height: 38.10343933105469,
                child: GeneratedUser_idWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 58.33802795410156,
                child: GeneratedDonationRequestWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 29.0,
                child: GeneratedNameWidget4(),
              ),
              Positioned(
                left: 366.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRequest_Donation_CCWidget1(),
              ),
              Positioned(
                left: 214.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 40.0,
                child: GeneratedNextWidget(),
              ),
              Positioned(
                left: 310.2940673828125,
                top: 111.308837890625,
                right: null,
                bottom: null,
                width: 26.470611572265625,
                height: 13.820632934570312,
                child: GeneratedGroup24Widget4(),
              )
            ]),
      ),
    ));
  }
}
