import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedPASTDONATIONSWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedDONATEWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedSignOutWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedHOTLISTWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedPARTNERSWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedCOMMUNITYWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedDONOR_USERNAMEWidget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/giftapp/generatedland_donorwidget/generated/GeneratedGroup25Widget.dart';

/* Frame Land_Donor
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLand_DonorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.941177368164062,
                top: -131.82723999023438,
                right: null,
                bottom: null,
                width: 314.7059326171875,
                height: 425.2491760253906,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 16.47058868408203,
                top: -130.23257446289062,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.5083236694336,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 135.29409790039062,
                top: 35.08305358886719,
                right: null,
                bottom: null,
                width: 89.41178894042969,
                height: 94.61793518066406,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 144.584716796875,
                right: null,
                bottom: null,
                width: 132.64706420898438,
                height: 26.262451171875,
                child: GeneratedDONOR_USERNAMEWidget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 313.0896911621094,
                right: null,
                bottom: null,
                width: 314.7059326171875,
                height: 67.50830078125,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 337.6470642089844,
                top: 236.01327514648438,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50836181640625,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 544.3189086914062,
                right: null,
                bottom: null,
                width: 314.7059326171875,
                height: 67.5084228515625,
                child: GeneratedRectangle42Widget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 544.3189086914062,
                right: null,
                bottom: null,
                width: 314.7059326171875,
                height: 67.5084228515625,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 390.16607666015625,
                right: null,
                bottom: null,
                width: 314.7059326171875,
                height: 67.50833129882812,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 467.2425537109375,
                right: null,
                bottom: null,
                width: 314.7059326171875,
                height: 67.50830078125,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 334.3521423339844,
                right: null,
                bottom: null,
                width: 319.7059326171875,
                height: 72.50833129882812,
                child: GeneratedDONATEWidget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 410.89703369140625,
                right: null,
                bottom: null,
                width: 316.7059326171875,
                height: 69.50827026367188,
                child: GeneratedPASTDONATIONSWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 319.7059326171875,
                height: 72.50830078125,
                child: GeneratedCOMMUNITYWidget(),
              ),
              Positioned(
                left: 22.941177368164062,
                top: 259.4019775390625,
                right: null,
                bottom: null,
                width: 319.7059326171875,
                height: 72.50830078125,
                child: GeneratedHOTLISTWidget(),
              ),
              Positioned(
                left: 285.2940979003906,
                top: 207.30894470214844,
                right: null,
                bottom: null,
                width: 26.470611572265625,
                height: 13.820632934570312,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 446.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 29.0,
                child: GeneratedSignOutWidget(),
              ),
              Positioned(
                left: 3.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 319.7059326171875,
                height: 72.50830078125,
                child: GeneratedPARTNERSWidget(),
              )
            ]),
      ),
    ));
  }
}
