import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedNameofCenterWidget.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedContactnumberWidget1.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedHOMEWidget3.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedSignupasaCollectionCenterWidget.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedConfirmPasswordWidget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedSignupWidget5.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedBACKWidget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedEmailAddressWidget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedCreatePasswordWidget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedGIFTOFTHEGIVERSWidget4.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/giftapp/generatedsignupccwidget/generated/GeneratedRectangle19Widget.dart';

/* Frame SIGNUP CC
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSIGNUPCCWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 63.4093017578125,
                child: GeneratedGIFTOFTHEGIVERSWidget4(),
              ),
              Positioned(
                left: 24.12297821044922,
                top: 594.5507202148438,
                right: null,
                bottom: null,
                width: 90.0085678100586,
                height: 31.05804443359375,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 39.10863494873047,
                top: 188.24615478515625,
                right: null,
                bottom: null,
                width: 290.8078308105469,
                height: 41.739131927490234,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 39.10863494873047,
                top: 259.9908142089844,
                right: null,
                bottom: null,
                width: 290.80780029296875,
                height: 41.739131927490234,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 39.10863494873047,
                top: 339.4189453125,
                right: null,
                bottom: null,
                width: 290.80780029296875,
                height: 41.73910140991211,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 39.10863494873047,
                top: 416.0269470214844,
                right: null,
                bottom: null,
                width: 290.80780029296875,
                height: 41.739131927490234,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 39.10863494873047,
                top: 487.1827392578125,
                right: null,
                bottom: null,
                width: 290.80780029296875,
                height: 41.73916244506836,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 39.36000061035156,
                top: 71.96401977539062,
                right: null,
                bottom: null,
                width: 284.239990234375,
                height: 61.49024963378906,
                child: GeneratedSignupasaCollectionCenterWidget(),
              ),
              Positioned(
                left: 40.11142349243164,
                top: 156.75363159179688,
                right: null,
                bottom: null,
                width: 292.8078308105469,
                height: 19.623184204101562,
                child: GeneratedNameofCenterWidget(),
              ),
              Positioned(
                left: 40.11142349243164,
                top: 230.0290069580078,
                right: null,
                bottom: null,
                width: 292.8078308105469,
                height: 19.623153686523438,
                child: GeneratedContactnumberWidget1(),
              ),
              Positioned(
                left: 40.11142349243164,
                top: 313.50726318359375,
                right: null,
                bottom: null,
                width: 292.8078308105469,
                height: 19.6231689453125,
                child: GeneratedEmailAddressWidget2(),
              ),
              Positioned(
                left: 40.11142349243164,
                top: 462.840576171875,
                right: null,
                bottom: null,
                width: 292.8078308105469,
                height: 19.6231689453125,
                child: GeneratedConfirmPasswordWidget2(),
              ),
              Positioned(
                left: 40.11142349243164,
                top: 392.34783935546875,
                right: null,
                bottom: null,
                width: 292.8078308105469,
                height: 19.6231689453125,
                child: GeneratedCreatePasswordWidget2(),
              ),
              Positioned(
                left: 23.064067840576172,
                top: 598.1343994140625,
                right: null,
                bottom: null,
                width: 95.00856018066406,
                height: 36.05804443359375,
                child: GeneratedBACKWidget2(),
              ),
              Positioned(
                left: 137.97909545898438,
                top: 554.6666870117188,
                right: null,
                bottom: null,
                width: 83.52001953125,
                height: 32.62371826171875,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 141.74215698242188,
                top: 564.588134765625,
                right: null,
                bottom: null,
                width: 78.24259948730469,
                height: 24.69622802734375,
                child: GeneratedSignupWidget5(),
              ),
              Positioned(
                left: 283.73748779296875,
                top: 588.2179565429688,
                right: null,
                bottom: null,
                width: 47.760040283203125,
                height: 37.53289794921875,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 255.89747619628906,
                top: 599.8660888671875,
                right: null,
                bottom: null,
                width: 109.20368957519531,
                height: 29.59051513671875,
                child: GeneratedHOMEWidget3(),
              )
            ]),
      ),
    ));
  }
}
