import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedCC_USERNAMEWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedSignOutWidget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedRectangle39Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedRectangle43Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedCOMMUNITYWidget1.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedRequestDONATIONWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedRectangle40Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedGroup24Widget3.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedRectangle41Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedInventoryWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedGroup25Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedRectangle42Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedDONATEWidget1.dart';
import 'package:flutterapp/giftapp/generatedland_ccwidget/generated/GeneratedPARTNERSWidget2.dart';

/* Frame Land_CC
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLand_CCWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.47058868408203,
                top: -130.23255920410156,
                right: null,
                bottom: null,
                width: 314.70587158203125,
                height: 425.2491455078125,
                child: GeneratedGroup25Widget2(),
              ),
              Positioned(
                left: 135.2941131591797,
                top: 35.08305358886719,
                right: null,
                bottom: null,
                width: 89.41177368164062,
                height: 94.61793518066406,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 110.0,
                top: 144.584716796875,
                right: null,
                bottom: null,
                width: 132.64706420898438,
                height: 26.262451171875,
                child: GeneratedCC_USERNAMEWidget(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 317.3421936035156,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50830078125,
                child: GeneratedRectangle39Widget2(),
              ),
              Positioned(
                left: 337.058837890625,
                top: 240.26577758789062,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50830078125,
                child: GeneratedRectangle43Widget2(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 548.5714111328125,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50836181640625,
                child: GeneratedRectangle42Widget2(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 394.4186096191406,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50830078125,
                child: GeneratedRectangle40Widget2(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 471.4950256347656,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50833129882812,
                child: GeneratedRectangle41Widget2(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 338.60467529296875,
                right: null,
                bottom: null,
                width: 319.7059020996094,
                height: 72.50830078125,
                child: GeneratedDONATEWidget1(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 415.1495056152344,
                right: null,
                bottom: null,
                width: 316.7059020996094,
                height: 69.50830078125,
                child: GeneratedRequestDONATIONWidget(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 572.49169921875,
                right: null,
                bottom: null,
                width: 319.7059020996094,
                height: 72.50830078125,
                child: GeneratedCOMMUNITYWidget1(),
              ),
              Positioned(
                left: 22.35293960571289,
                top: 494.3521423339844,
                right: null,
                bottom: null,
                width: 319.7059020996094,
                height: 72.50833129882812,
                child: GeneratedPARTNERSWidget2(),
              ),
              Positioned(
                left: 18.823528289794922,
                top: 246.1129608154297,
                right: null,
                bottom: null,
                width: 319.7059326171875,
                height: 72.50831604003906,
                child: GeneratedInventoryWidget(),
              ),
              Positioned(
                left: 285.29412841796875,
                top: 207.3089599609375,
                right: null,
                bottom: null,
                width: 26.4705810546875,
                height: 13.82061767578125,
                child: GeneratedGroup24Widget3(),
              ),
              Positioned(
                left: 446.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 29.0,
                child: GeneratedSignOutWidget2(),
              )
            ]),
      ),
    ));
  }
}
