import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedSignupWidget1.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedSignupWidget2.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedDonationsaremadetoaccodingtoasystemthataWidget.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedHAVINGTROUBLEDECIDINGWHERETOMAKEANIMPACTFULLDONATIONWeg.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedGIFTOFTHEGIVERSWidget.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedImages1Widget.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedSignupWidget.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/giftapp/generatedhomepagewidget/generated/GeneratedRectangle9Widget.dart';

/* Frame Home page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -53.645233154296875,
                right: null,
                bottom: null,
                width: 394.42230224609375,
                height: 228.30410766601562,
                child: GeneratedImages1Widget(),
              ),
              Positioned(
                left: 25.816734313964844,
                top: 200.85769653320312,
                right: null,
                bottom: null,
                width: 314.6693115234375,
                height: 25.703704833984375,
                child: GeneratedGIFTOFTHEGIVERSWidget(),
              ),
              Positioned(
                left: 197.9282989501953,
                top: 9.980506896972656,
                right: null,
                bottom: null,
                width: 86.62150573730469,
                height: 18.21832275390625,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 296.4705505371094,
                top: 4.81203031539917,
                right: null,
                bottom: null,
                width: 65.52944946289062,
                height: 22.451129913330078,
                child: GeneratedSignupWidget(),
              ),
              Positioned(
                left: 44.46215057373047,
                top: 289.43475341796875,
                right: null,
                bottom: null,
                width: 271.6414489746094,
                height: 86.834228515625,
                child:
                    GeneratedHAVINGTROUBLEDECIDINGWHERETOMAKEANIMPACTFULLDONATIONWeg(),
              ),
              Positioned(
                left: 126.21514129638672,
                top: 562.6510620117188,
                right: null,
                bottom: null,
                width: 124.78087615966797,
                height: 46.15985107421875,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 25.816734313964844,
                top: 426.66668701171875,
                right: null,
                bottom: null,
                width: 310.36651611328125,
                height: 56.892730712890625,
                child:
                    GeneratedDonationsaremadetoaccodingtoasystemthataWidget(),
              ),
              Positioned(
                left: 136.25497436523438,
                top: 573.879150390625,
                right: null,
                bottom: null,
                width: 105.26695251464844,
                height: 25.7037353515625,
                child: GeneratedSignupWidget1(),
              ),
              Positioned(
                left: 126.21514129638672,
                top: 562.6510620117188,
                right: null,
                bottom: null,
                width: 124.78087615966797,
                height: 46.15985107421875,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 136.25497436523438,
                top: 572.6315307617188,
                right: null,
                bottom: null,
                width: 105.26695251464844,
                height: 25.7037353515625,
                child: GeneratedSignupWidget2(),
              )
            ]),
      ),
    ));
  }
}
