import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedRectangle13Widget6.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedLogInAsWidget.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedHOMEWidget13.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedDONORWidget1.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedCOLLECTIONCENTERWidget1.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedRectangle12Widget4.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedGIFTOFTHEGIVERSWidget11.dart';
import 'package:flutterapp/giftapp/generatedlog_in_aswidget/generated/GeneratedNGOWidget1.dart';

/* Frame Log_In_As
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLog_In_AsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 53.0,
              top: 426.0,
              right: null,
              bottom: null,
              width: 259.9999694824219,
              height: 53.0,
              child: GeneratedRectangle11Widget1(),
            ),
            Positioned(
              left: 53.0,
              top: 343.0,
              right: null,
              bottom: null,
              width: 259.9999694824219,
              height: 53.0,
              child: GeneratedRectangle12Widget4(),
            ),
            Positioned(
              left: 53.0,
              top: 251.0,
              right: null,
              bottom: null,
              width: 259.9999694824219,
              height: 53.0,
              child: GeneratedRectangle13Widget6(),
            ),
            Positioned(
              left: 71.99998474121094,
              top: 268.79913330078125,
              right: null,
              bottom: null,
              width: 225.80787658691406,
              height: 24.0,
              child: GeneratedDONORWidget1(),
            ),
            Positioned(
              left: 69.99998474121094,
              top: 356.5633544921875,
              right: null,
              bottom: null,
              width: 228.3755645751953,
              height: 40.0,
              child: GeneratedCOLLECTIONCENTERWidget1(),
            ),
            Positioned(
              left: 107.0,
              top: 443.0,
              right: null,
              bottom: null,
              width: 156.0,
              height: 24.0,
              child: GeneratedNGOWidget1(),
            ),
            Positioned(
              left: 44.999996185302734,
              top: 130.28382873535156,
              right: null,
              bottom: null,
              width: 278.48468017578125,
              height: 140.29258728027344,
              child: GeneratedLogInAsWidget(),
            ),
            Positioned(
              left: 57.0,
              top: 62.0,
              right: null,
              bottom: null,
              width: 252.00003051757812,
              height: 42.0,
              child: GeneratedGIFTOFTHEGIVERSWidget11(),
            ),
            Positioned(
              left: 166.0,
              top: 571.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 29.0,
              child: GeneratedRectangle10Widget2(),
            ),
            Positioned(
              left: 147.0,
              top: 581.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 24.0,
              child: GeneratedHOMEWidget13(),
            )
          ]),
    ));
  }
}
