import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedpbupwidget/generated/GeneratedMenuWidget.dart';

/* Component pbup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPbupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 245.0,
      height: 487.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(73, 147, 75, 15),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 245.0,
              height: 487.0,
              child: GeneratedMenuWidget(),
            )
          ]),
    ));
  }
}
