import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedTrackOrderWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedSignOutWidget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedCommunityWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedPastRequestsWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedGroup24Widget2.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedNGO_USERNAMEWidget.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedPARTNERSWidget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/giftapp/generatedland_ngowidget/generated/GeneratedRequestDonationWidget.dart';

/* Frame Land_ngo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLand_ngoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.47058868408203,
                top: -130.23257446289062,
                right: null,
                bottom: null,
                width: 314.70587158203125,
                height: 425.2491760253906,
                child: GeneratedGroup25Widget1(),
              ),
              Positioned(
                left: 135.2941131591797,
                top: 35.08305358886719,
                right: null,
                bottom: null,
                width: 89.41177368164062,
                height: 94.61793518066406,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 110.0,
                top: 144.584716796875,
                right: null,
                bottom: null,
                width: 132.64706420898438,
                height: 26.262451171875,
                child: GeneratedNGO_USERNAMEWidget(),
              ),
              Positioned(
                left: 22.941173553466797,
                top: 327.97344970703125,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50827026367188,
                child: GeneratedRectangle39Widget1(),
              ),
              Positioned(
                left: 337.6470642089844,
                top: 250.89700317382812,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50833129882812,
                child: GeneratedRectangle43Widget1(),
              ),
              Positioned(
                left: 22.941173553466797,
                top: 559.20263671875,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50830078125,
                child: GeneratedRectangle42Widget1(),
              ),
              Positioned(
                left: 22.941173553466797,
                top: 405.0498046875,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50833129882812,
                child: GeneratedRectangle40Widget1(),
              ),
              Positioned(
                left: 22.941173553466797,
                top: 482.126220703125,
                right: null,
                bottom: null,
                width: 314.7059020996094,
                height: 67.50830078125,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: 22.941173553466797,
                top: 349.2358703613281,
                right: null,
                bottom: null,
                width: 316.7059020996094,
                height: 69.50833129882812,
                child: GeneratedPastRequestsWidget(),
              ),
              Positioned(
                left: 22.941173553466797,
                top: 425.78070068359375,
                right: null,
                bottom: null,
                width: 316.7059020996094,
                height: 69.50833129882812,
                child: GeneratedTrackOrderWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 319.7059020996094,
                height: 72.50830078125,
                child: GeneratedCommunityWidget(),
              ),
              Positioned(
                left: 16.47058868408203,
                top: 252.49166870117188,
                right: null,
                bottom: null,
                width: 316.70587158203125,
                height: 69.50833129882812,
                child: GeneratedRequestDonationWidget(),
              ),
              Positioned(
                left: 485.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 26.0,
                child: GeneratedGroup24Widget2(),
              ),
              Positioned(
                left: 446.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 29.0,
                child: GeneratedSignOutWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 319.7059020996094,
                height: 72.50836181640625,
                child: GeneratedPARTNERSWidget1(),
              )
            ]),
      ),
    ));
  }
}
