import 'package:flutter/material.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedConfirmPasswordWidget4.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedRectangle28Widget4.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedRectangle22Widget5.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedNewPasswordWidget1.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedRectangle36Widget1.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedUser_idWidget4.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedCHANGEPASSWORDWidget1.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedRectangle21Widget6.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedSavechangesWidget4.dart';
import 'package:flutterapp/giftapp/generatedchange_pass_ngowidget/generated/GeneratedEmailAddressWidget7.dart';

/* Frame Change_Pass_NGO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChange_Pass_NGOWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 112.16617584228516,
                top: 73.78823852539062,
                right: null,
                bottom: null,
                width: 136.73590087890625,
                height: 88.8470458984375,
                child: GeneratedRectangle28Widget4(),
              ),
              Positioned(
                left: 41.57688522338867,
                top: 267.54736328125,
                right: null,
                bottom: null,
                width: 276.41656494140625,
                height: 53.23094177246094,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 9.61424446105957,
                top: 215.34115600585938,
                right: null,
                bottom: null,
                width: 342.771484375,
                height: 35.12944030761719,
                child: GeneratedEmailAddressWidget7(),
              ),
              Positioned(
                left: 82.25518798828125,
                top: 594.8235473632812,
                right: null,
                bottom: null,
                width: 194.42135620117188,
                height: 33.12939453125,
                child: GeneratedRectangle36Widget1(),
              ),
              Positioned(
                left: 32.04747772216797,
                top: 585.7882080078125,
                right: null,
                bottom: null,
                width: 298.9732666015625,
                height: 56.2117919921875,
                child: GeneratedSavechangesWidget4(),
              ),
              Positioned(
                left: 82.25518798828125,
                top: 168.65882873535156,
                right: null,
                bottom: null,
                width: 200.4896240234375,
                height: 39.63529968261719,
                child: GeneratedUser_idWidget4(),
              ),
              Positioned(
                left: 41.57688522338867,
                top: 367.4432373046875,
                right: null,
                bottom: null,
                width: 276.4109191894531,
                height: 53.2364501953125,
                child: GeneratedRectangle21Widget6(),
              ),
              Positioned(
                left: 41.57688522338867,
                top: 477.5451354980469,
                right: null,
                bottom: null,
                width: 276.4109191894531,
                height: 53.23638916015625,
                child: GeneratedRectangle22Widget5(),
              ),
              Positioned(
                left: 9.61424446105957,
                top: 435.20001220703125,
                right: null,
                bottom: null,
                width: 342.771484375,
                height: 33.62353515625,
                child: GeneratedConfirmPasswordWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 323.7646789550781,
                right: null,
                bottom: null,
                width: 362.0,
                height: 33.62353515625,
                child: GeneratedNewPasswordWidget1(),
              ),
              Positioned(
                left: 9.61424446105957,
                top: 0.0,
                right: null,
                bottom: null,
                width: 342.771484375,
                height: 75.78823852539062,
                child: GeneratedCHANGEPASSWORDWidget1(),
              )
            ]),
      ),
    ));
  }
}
